services:
  ml_service:
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'

  api:
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.5'

  web:
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.5'

  prometheus:
    profiles:
      - monitoring

  grafana:
    profiles:
      - monitoring
