[pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
addopts =
    --cov=etl
    --cov=ml_service
    --cov-report=term-missing
    --cov-report=html:coverage_report/html
    --cov-report=xml:coverage_report/coverage.xml
